# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{rake_server}
  s.version = "0.0.4"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Mat Brown", "Cedric Howe"]
  s.date = %q{2010-04-07}
  s.description = %q{RakeServer is a library which allows Rake tasks to be run using client requests
to a long-running rake server, which can eagerly load required code into memory
for fast task invocation.
}
  s.email = %q{mat@patch.com}
  s.executables = ["rake-client", "rake-server"]
  s.extra_rdoc_files = [
    "README.rdoc",
     "TODO"
  ]
  s.files = [
    "README.rdoc",
     "Rakefile",
     "TODO",
     "VERSION",
     "bin/rake-client",
     "bin/rake-server",
     "lib/rake_server.rb",
     "lib/rake_server/client.rb",
     "lib/rake_server/server.rb",
     "pkg/.gitignore",
     "rake_server.gemspec",
     "tasks/gemspec.rake",
     "test/Rakefile",
     "tmp/.gitignore"
  ]
  s.homepage = %q{http://github.com/outoftime/rake_server}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{Run rake tasks in a client-server architecture}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

